name: rust CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > installer
          chmod +x installer
          ./installer -y
          rustup default nightly
          rustc --version
      - name: Build
        run: cargo build --workspace --features bundled
      - name: Test
        run: |
          cargo test --workspace --features bundled
          cargo test --workspace --release --features bundled
